#! /bin/bash

set -o errexit
set -o nounset
set -o pipefail

LKDEV_ROOT=$(dirname "${BASH_SOURCE}")
KDIR="${LKDEV_ROOT}/../linux"
KBUILD_OUTPUT="${KDIR}/build"
BASE_TARGET_DIR="base"

PACKAGES=(systemd)


source "${LKDEV_ROOT}/lib/util.sh"

util::defer util::print_stack


sudo mkdir -p "${BASE_TARGET_DIR}/etc/ssl/certs/"

sudo cp /etc/ssl/certs/ca-certificates.crt "${BASE_TARGET_DIR}/etc/ssl/certs/"

bash arch-bootstrap.sh "${BASE_TARGET_DIR}/"

LC_ALL=C chroot "${BASE_TARGET_DIR}" /usr/bin/pacman \
    --noconfirm -Sy --force ${PACKAGES[@]}

chroot "${BASE_TARGET_DIR}" ln -fs /usr/lib/systemd/systemd /sbin/init

# Make root passwordless for convenience.
sudo sed -i '/^root/ { s/:x:/::/ }' "${BASE_TARGET_DIR}/etc/passwd"
# Add a getty on the virtio console
#echo 'V0:23:respawn:/sbin/getty 115200 hvc0' | sudo tee -a "${BASE_TARGET_DIR}/etc/inittab"
# Automatically bring up enp0s4 using DHCP
# printf '\nsource-directory /etc/network/interfaces.d\n\nauto eth0\niface eth0 inet dhcp\n' | sudo tee "${BASE_TARGET_DIR}/etc/network/interfaces"
# Set up my ssh pubkey for root in the VM
sudo mkdir -p "${BASE_TARGET_DIR}/root/.ssh/"
cat ~/.ssh/id_?sa.pub | sudo tee "${BASE_TARGET_DIR}"/root/.ssh/authorized_keys

# kernel modules
sudo rm -rf "${BASE_TARGET_DIR}/lib/modules"
sudo make -C "${KDIR}" O="${KBUILD_OUTPUT}" INSTALL_MOD_PATH="${PWD}/${BASE_TARGET_DIR}" modules_install
sudo make -C "${KDIR}" O="${KBUILD_OUTPUT}" INSTALL_HDR_PATH="${PWD}/${BASE_TARGET_DIR}/usr" headers_install
