#! /bin/bash

set -o errexit
set -o nounset
set -o pipefail

install_dir() {
  local src="${1}"
  local dst="${2}"

  for f in $(find "${src}" -type f); do
    local t="${f#${src}}"
    mkdir -p "$(dirname "${t}")"
    cp --preserve=mode,timestamps ${f} ${t}
  done
}

install_dir /var/kernel-modules /
install_dir /var/kernel-headers /
