#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

setup_ipvlan() {
  NS0="${MODE}-ns0"
  NS1="${MODE}-ns1"
  IPV0="${MODE}-ipv0"
  IPV1="${MODE}-ipv1"

  ip netns add "${NS0}"
  ip netns add "${NS1}"

  ip link add "ipvH${ETH}" link "${ETH}" type ipvlan mode "${MODE}"
  ip link set "ipvH${ETH}" up
  ip addr add "192.168.${NET_NUM}.9/24" dev "ipvH${ETH}"

  ip link add "${IPV0}" link "${ETH}" type ipvlan mode "${MODE}"
  ip link add "${IPV1}" link "${ETH}" type ipvlan mode "${MODE}"

  ip link set "${IPV0}" netns "${NS0}"
  ip link set "${IPV1}" netns "${NS1}"

  ip netns exec "${NS0}" ip link set "${IPV0}" name eth0
  ip netns exec "${NS0}" ip link set dev eth0 up

  ip netns exec "${NS1}" ip link set "${IPV1}" name eth0
  ip netns exec "${NS1}" ip link set dev eth0 up

  ip netns exec "${NS0}" ip link set lo up
  ip netns exec "${NS0}" ip addr add "192.168.${NET_NUM}.10/24" dev eth0
  ip netns exec "${NS0}" ip link set eth0 up
  ip netns exec "${NS0}" ip route add default dev eth0

  ip netns exec "${NS1}" ip link set lo up
  ip netns exec "${NS1}" ip addr add "192.168.${NET_NUM}.11/24" dev eth0
  ip netns exec "${NS1}" ip link set eth0 up
  ip netns exec "${NS1}" ip route add default dev eth0
}

MODE="l3s"
ETH="enp0s4"
NET_NUM="4"

setup_ipvlan

#MODE="l3"
#ETH="enp0s5"
#NET_NUM="5"
#
#setup_ipvlan
#
#MODE="l2"
#ETH="enp0s6"
#NET_NUM="6"
#
#setup_ipvlan
