#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

cat <<EOF > /etc/apt/sources.list.d/iovisor.list
deb [trusted=yes] http://52.8.15.63/apt/xenial xenial-nightly main
EOF

apt-get update
apt-get install -y \
  bcc-tools \
  git \
  vim \
  htop \
  conntrack
apt-get upgrade -y
