#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

cat <<EOF > /etc/apt/sources.list.d/iovisor.list
deb [trusted=yes] http://52.8.15.63/apt/xenial xenial-nightly main
EOF

apt-get update
apt-get install -y \
  bcc-tools \
  git \
  vim \
  htop \
  conntrack \
  libdwarf-dev libunwind8-dev lzma-dev libdwarf-dev libaudit-dev libelf-dev \
  libnuma-dev libperl-dev libpython-dev libslang2-dev libdwarf-dev libaudit-dev libelf-dev \
  systemtap
apt-get upgrade -y
